version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run install:lambda
  build:
    commands:
      - npm run deploy:ci
  post_build:
    commands:
      - npm run test:remote