service: remint

custom:
  defaultStage: dev
  profiles:
    dev: dev
    prod: prod
    test: dev

provider:
  name: aws
  runtime: nodejs6.10
  stage:  ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  tracing: true

functions:
  remint:
    environment:
      SECRET: ${ssm:/remint/secret~true}
      TTL: 40
    handler: handler.remint
    events:
     - http:
        path: remint/{id}
        method: get
        cors: true

plugins:
  - serverless-offline
  - serverless-plugin-tracing