service: remint

provider:
  name: aws
  runtime: nodejs6.10

functions:
  remint:
    environment:
      SECRET: ${ssm:/remint/secret~true}
      TTL: 40
    handler: handler.remint
    events:
     - http:
        path: remint/{id}
        method: get
        cors: true

plugins:
  - serverless-offline
