service: remint

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  deploymentBucket:
      name: com.nuskin.us-west-2.deploys
      serverSideEncryption: AES256 # when using server-side encryption

functions:
  remint:
    environment:
      SECRET: ${ssm:/remint/secret~true}
      TTL: 40
    handler: handler.remint
    events:
     - http:
        path: remint
        method: get
        cors: true
plugins:
  - serverless-offline
