service: remint

provider:
  name: aws
  runtime: nodejs6.10
  tracing: true
  deploymentBucket:
      name: com.nuskin.${self:provider.region}.deploys
      serverSideEncryption: AES256 # when using server-side encryption
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "xray:PutTraceSegments"
       - "xray:PutTelemetryRecords"
     Resource:
       - "*"

functions:
  remint:
    environment:
      SECRET: ${ssm:/remint/secret~true}
      TTL: 40
    handler: handler.remint
    events:
     - http:
        path: remint
        method: get
        cors: true
  mint:
      environment:
        SECRET: ${ssm:/remint/secret~true}
      handler: handler.mint
      events:
       - http:
          path: mint
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-tracing