AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Remint:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /remint:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Remint.Arn}/invocations
              responses: {}
  RemintLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Remint
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Remint
      Principal: apigateway.amazonaws.com
